export const PAY_ORDER_REQUEST = "PAY_ORDER_REQUEST";
export const PAY_ORDER_SUCCESS = "PAY_ORDER_SUCCESS";
export const PAY_ORDER_FAIL = "PAY_ORDER_FAIL";

export const GET_ORDER_REQUEST = "GET_ORDER_REQUEST";
export const GET_ORDER_SUCCESS = "GET_ORDER_SUCCESS";
export const GET_ORDER_FAIL = "GET_ORDER_FAIL";
export const GET_ORDER_RESET = "GET_ORDER_RESET";

export const CUSTOMER_ORDERS_REQUEST = "CUSTOMER_ORDERS_REQUEST";
export const CUSTOMER_ORDERS_SUCCESS = "CUSTOMER_ORDERS_SUCCESS";
export const CUSTOMER_ORDERS_FAIL = "CUSTOMER_ORDERS_FAIL";
export const CUSTOMER_ORDERS_RESET = "CUSTOMER_ORDERS_RESET";

export const CREATE_ORDER_REQUEST = "CREATE_ORDER_REQUEST";
export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS";
export const CREATE_ORDER_FAIL = "CREATE_ORDER_FAIL";
export const CREATE_ORDER_RESET = "CREATE_ORDER_RESET";
