export const GET_PRODUCT_REQUEST = "GET_PRODUCT_REQUEST";
export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS";
export const GET_PRODUCT_FAIL = "GET_PRODUCT_FAIL";
export const GET_PRODUCT_RESET = "GET_PRODUCT_RESET";

export const GET_LINEUPS_REQUEST = "GET_LINEUPS_REQUEST";
export const GET_LINEUPS_SUCCESS = "GET_LINEUPS_SUCCESS";
export const GET_LINEUPS_FAIL = "GET_LINEUPS_FAIL";
export const GET_LINEUPS_RESET = "GET_LINEUPS_RESET";
